# Generated by Django 5.2.17 on 2026-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('device_type', models.CharField(max_length=120)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINT', 'Maintenance'), ('OOS', 'Out of Service'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=20)),
                ('installation_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
