# Generated by Django 5.2.17 on 2026-09-14 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operators', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('specimen_type', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(blank=True, max_length=120)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='operators.operator')),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competency.testmethod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operator', 'test_method', 'expiration_date'), name='unique_operator_test_expiration')],
            },
        ),
    ]
