# Generated by Django 5.2.17 on 2026-09-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('REAGENT', 'Reagent'), ('CONTROL', 'Control'), ('CARTRIDGE', 'Cartridge'), ('STRIP', 'Test Strip'), ('CONSUMABLE', 'Consumable')], max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('storage_location', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
