# Generated by Django 5.2.17 on 2026-09-14 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competency', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualityControlRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_level', models.CharField(max_length=50)),
                ('lot_number', models.CharField(max_length=100)),
                ('result', models.FloatField()),
                ('lower_limit', models.FloatField()),
                ('upper_limit', models.FloatField()),
                ('performed_at', models.DateTimeField()),
                ('corrective_action', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('test_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competency.testmethod')),
            ],
        ),
    ]
